name: Lade Login Automation (检查登录成功)

on:
  push:
    branches:
      - main

jobs:
  login-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install expect and Lade CLI
        run: |
          sudo apt-get install -y expect
          curl -L https://github.com/lade-io/lade/releases/latest/download/lade-linux-amd64.tar.gz | tar xz
          sudo mv lade /usr/local/bin

      - name: Automate Lade login
        run: |
          cat <<EOF > login_expect_script.sh
          #!/usr/bin/expect -f

          set timeout 20
          spawn lade login

          expect {
              "Username or email:" { send "hwuli0125@gmail.com\r" }
          }

          expect {
              "Password:" { send "GuBD5KdtLqIgDUhv3UUf\r" }
          }

          expect eof
          EOF

          chmod +x login_expect_script.sh
          ./login_expect_script.sh

      - name: Check if login is successful
        run: |
          # 使用 lade whoami 检查登录是否成功
          result=$(lade whoami)
          echo "Login result: $result"

          if [[ "$result" == *"Logged in as"* ]]; then
              echo "✅ Login successful!"
          else
              echo "❌ Login failed. Please check the login credentials."
              exit 1
          fi
