name: Run ttyd with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  run-ttyd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and install ttyd
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar

          wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd_linux.x86_64.tar.gz
          tar -xvzf ttyd_linux.x86_64.tar.gz
          sudo mv ttyd /usr/local/bin/

          ttyd --version

      - name: Start ttyd server
        run: |
          # 启动 ttyd，监听 7681 端口，后台运行
          nohup ttyd -p 7681 bash &

      - name: Download and run Cloudflare Tunnel
        run: |
          # 下载 cloudflared
          wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared

          # 启动 cloudflared 隧道，自动随机子域名
          ./cloudflared tunnel --edge-ip-version auto --no-autoupdate --logfile argo.log --loglevel info --url http://localhost:7681 2>&1 &

          # 等待隧道启动
          sleep 5

          # 打印 tunnel 地址
          cat argo.log | grep -o "info.*https://.*trycloudflare.com" | sed "s@.*https://@@g" | tail -n 1

