name: Run ttyd with Cloudflare Tunnel

on:
  push:
    branches:
      - main

jobs:
  run-ttyd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and install ttyd
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar jq

          if [ ! -e ttyd ]; then
               URL=$(wget -qO- "https://api.github.com/repos/tsl0922/ttyd/releases/latest" | jq -r '.assets[] | select(.name|test("x86_64")) | .browser_download_url')
               if [ -z "$URL" ]; then
                   URL=https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64
               fi
               wget -O ttyd "$URL"
               chmod +x ttyd
          fi

          ./ttyd --version

      - name: Start ttyd server
        run: |
          nohup ./ttyd -p 7681 bash > ttyd.log 2>&1 &

      - name: Download and run Cloudflare Tunnel
        run: |
          wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared

          nohup ./cloudflared tunnel --edge-ip-version auto --no-autoupdate --logfile argo.log --loglevel info --url http://localhost:7681 > cloudflared.log 2>&1 &

          echo "Waiting for Cloudflare Tunnel to start..."
          sleep 10

          # 获取并输出 Tunnel 地址
          TUNNEL_URL=$(grep -o 'https://[^ ]*trycloudflare.com' argo.log | head -n 1)
          if [ -n "$TUNNEL_URL" ]; then
              echo "✅ 你的远程访问地址: $TUNNEL_URL"
          else
              echo "❌ 获取 Tunnel 地址失败，请检查 argo.log 日志。"
              cat argo.log
              exit 1
          fi
